---
platform: linux
image_resource:
  type: registry-image
  source: { repository: golang, tag: 1.16.0 }

inputs:
  - name: terraform-provider-alicloud
run:
  path: sh
  args:
    - -cx
    - |
      chmod +rx terraform-provider-alicloud/ci/tasks/package.sh
      terraform-provider-alicloud/ci/tasks/package.sh

