---
groups:
  - name: All
    jobs:
      - point-to-module-test

resources:
  - name: terraform-provider-alicloud
    type: git
    source:
      uri: https://github.com/Wanghx0991/terraform-provider-alicloud.git
      branch: master

  - name: terraform_module_test
    type: git
    source:
      uri: https://github.com/Wanghx0991/terraform_test
      branch: master


shared:
  - &validate
    task: validate
    file: terraform-provider-alicloud/ci/tasks/module-test.yml
    params: &validate-params
      ALICLOUD_ACCESS_KEY: {{alicloud_access_key}}
      ALICLOUD_SECRET_KEY: {{alicloud_secret_key}}
      ALICLOUD_REGION: {{alicloud_region}}
      terraform_version: {{terraform_version}}


jobs:
  - name: point-to-module-test
    serial: true
    plan:
      - get: terraform-provider-alicloud
        trigger: true
        resource: terraform-provider-alicloud
      - get: terraform_module_test
        trigger: false
        resource: terraform_module_test
      - task: build-next-provider
        file: terraform-provider-alicloud/ci/tasks/build-provider-next.yml
      - <<: *validate
        params:
          <<: *validate-params
          terraform_version: "0.13.7"


