---
groups:
  - name: All
    jobs:
      - verify-terraform-prev
      - verify-terraform-next

shared:
  - &validate
    task: validate
    file: terraform-provider-alicloud/ci/tasks/module-test.yml
    params: &validate-params
      ALICLOUD_ACCESS_KEY: {{alicloud_access_key}}
      ALICLOUD_SECRET_KEY: {{alicloud_secret_key}}
      ALICLOUD_REGION: {{alicloud_region}}
      terraform_version: {{terraform_version}}


jobs:
  - name: verify-terraform-prev
    serial: true
    plan:
      # 通过Github合码触发
      - get: terraform-provider-alicloud
        trigger: true
        resource: terraform-provider-alicloud
      # 用aliyun-cli 从远端去拉上一个版本的provider
      - get: aliyun-cli
        trigger: false
        resource: aliyun-cli
#        用上一个版本的provider去跑module
      - <<: *validate
        params:
          <<: *validate-params
          Stage: "prev"





resources:
  - name: terraform-provider-alicloud
    type: git
    source:
      uri: https://github.com/Wanghx0991/terraform-provider-alicloud.git
      branch: master
  - name: aliyun-cli
    type: s3
    source:
      access_key_id: {{aliyun_cli_access_key}}
      secret_access_key: {{aliyun_cli_secret_key}}
      bucket_name: {{aliyun_cli_bucket}}
      region_name: {{aliyun_cli_region}}