---
groups:
  - name: All
    jobs:
      - verify-terraform-prev
      - verify-terraform-next

resources:
  - name: terraform-provider-alicloud
    type: git
    source:
      uri: https://github.com/Wanghx0991/terraform-provider-alicloud.git
      branch: master
  - name: aliyun-cli
    type: s3
    source:
      access_key_id: {{aliyun_cli_access_key}}
      secret_access_key: {{aliyun_cli_secret_key}}
      bucket_name: {{aliyun_cli_bucket}}
      region_name: {{aliyun_cli_region}}


shared:
  - &validate
    task: validate
    file: terraform-provider-alicloud/ci/tasks/module-test.yml
    params: &validate-params
      ALICLOUD_ACCESS_KEY: {{alicloud_access_key}}
      ALICLOUD_SECRET_KEY: {{alicloud_secret_key}}
      ALICLOUD_REGION: {{alicloud_region}}
      terraform_version: {{terraform_version}}


jobs:
  - name: verify-terraform-prev
    serial: true
    plan:
      - get: terraform-provider-alicloud
        trigger: true
        resource: terraform-provider-alicloud
      - get: aliyun-cli
        trigger: false
        resource: aliyun-cli
      - task: build-next-provider
        file: terraform-provider-alicloud/ci/tasks/build-provider-next.yml
      - <<: *validate
        params:
          <<: *validate-params
          terraform_version: "0.13.7"
          CONCOURSE_TARGET_TRIGGER_PIPELINE_JOB_NAME: "certify-terraform-v13"
  - name: verify-terraform-next
    serial: true
    plan:
      - get: terraform-provider-alicloud
        trigger: true
        resource: terraform-provider-alicloud
        passed: [verify-terraform-prev]
      - get: aliyun-cli
        trigger: false
        resource: aliyun-cli
      - task: build-next-provider
        file: terraform-provider-alicloud/ci/tasks/build-provider-next.yml
      - <<: *validate
        params:
          <<: *validate-params
          terraform_version: "0.14.11"
          CONCOURSE_TARGET_TRIGGER_PIPELINE_JOB_NAME: "certify-terraform-v14"