---
platform: linux
image_resource:
  type: registry-image
  source: {repository: golang, tag: 1.16.0}
groups:
  - name: All
    jobs:
      - point-to-module-test


resources:
  - name: terraform-provider-alicloud
    type: git
    source:
      uri: https://github.com/Wanghx0991/terraform-provider-alicloud.git
      branch: master
#      paths:
#        - alicloud/*
#        - ci/*
#        - go.mod
#        - main.go

  - name: terraform_module_test
    type: git
    source:
      uri: https://github.com/Wanghx0991/terraform_test.git
      branch: master

jobs:
  - name: point-to-module-test
#    serial: true
    plan:
      - get: terraform-provider-alicloud
        trigger: true
      - get: terraform_module_test
        trigger: false
      - task: point-to-module-ci-test
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: {repository: golang, tag: 1.16.0}
          inputs:
          - name: terraform-provider-alicloud
          - name: terraform_module_test
          params:
            ALICLOUD_ACCESS_KEY: ""
            ALICLOUD_SECRET_KEY: ""
            ALICLOUD_REGION: ""
            terraform_version: ""
          run:
            path: sh
            args:
              - -cx
              - |
                ls -al
                cd terraform-provider-alicloud
                ./ci/tasks/module-test.sh

