name: Terrafrom Basic Test Process
on:
  push:
    paths:
      - .github/workflows/acctest-terraform-basic.yml
      - alicloud/*.go
    branches:
      - master
  pull_request:
    paths:
      - .github/workflows/acctest-terraform-basic.yml
      - alicloud/*.go

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go Version
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Get dependencies
        run: |
          go env
          echo "current = $(pwd)"
          echo "GOPATH = ${GOPATH}"
          sudo make dependency
          go get golang.org/x/tools/cmd/goimports
          go mod tidy
          go mod vendor
          echo "GOPATH = ${GOPATH}"
      - name: vet
        run: |
          sudo make vet

      - name: fmt
        run: |
          sudo make fmt

      - name: test
        run: |
          make test

      - name: fmtcheck
        run: |
          make fmtcheck



  field-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '3'
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.7'
      - name: mkdir
        run: |
          sudo mkdir -p "${GOPATH}/src/github.com/aliyun"
          chmod +rwx scripts/version_check.sh
      - name: Field Check
        run: |
          sudo bash scripts/version_check.sh