name: Terrafrom Basic Test Process
on:
  push:
    paths:
      - .github/workflows/acctest-terraform-basic.yml
      - alicloud/*.go
    branches:
      - master
  pull_request:
    paths:
      - .github/workflows/acctest-terraform-basic.yml
      - alicloud/*.go

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go Version
        uses: actions/setup-go@37335c7bb261b353407cff977110895fa0b4f7d8
        with:
          go-version: ^1.16

      - name: Get dependencies
        run: |
          sudo mkdir -p "/root/go/src/github.com/aliyun"
          sudo git clone "https://github.com/aliyun/terraform-provider-alicloud" /root/go/src/github.com/aliyun/terraform-provider-alicloud-prev
          sudo go mod edit -require=github.com/aliyun/terraform-provider-alicloud-prev@v0.0.0
          sudo go mod edit -replace github.com/aliyun/terraform-provider-alicloud-prev=/root/go/src/github.com/aliyun/terraform-provider-alicloud-prev
          go mod tidy
          go mod vendor
          go get golang.org/x/tools/cmd/goimports
          go mod tidy

      - name: vet
        run: |
          make vet

      - name: fmt
        run: |
          make fmt

      - name: test
        run: |
          make test

      - name: fmtcheck
        run: |
          make fmtcheck



  field-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '3'
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.7'
      - name: mkdir
        run: |
          sudo mkdir -p "${GOPATH}/src/github.com/aliyun"
          chmod +rwx scripts/version_check.sh
      - name: Field Check
        run: |
          sudo bash scripts/version_check.sh