name: Test Process
on:
  push:
    paths:
      - .github/workflows/ci_test.yml
      - .go-version
      - alicloud/*_test.go
      - scripts/validate-terraform.sh
      - tools/go.mod
    branches:
      - master
  pull_request:
    paths:
      - .github/workflows/ci_test.yml
      - .go-version
      - alicloud/*_test.go
      - scripts/validate-terraform.sh
      - tools/go.mod

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@37335c7bb261b353407cff977110895fa0b4f7d8
        with:
          go-version: ^1.16
      - name: Check out code into the Go module directory
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: Get dependencies
        run: |
          go get golang.org/x/tools/cmd/goimports
          go mod tidy

      - name: vet
        run: |
          make vet

      - name: fmt
        run: |
          make fmt

      - name: test
        run: |
          make test

      - name: fmtcheck
        run: |
          make fmtcheck


