name: Documentation Checks
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/document-check.yml
      - .go-version
      - website/docs/**

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          folder-path: "website/docs"
          file-extension: '.md'
  misspell:
    name: runner/misspell
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v1
      - name: misspell
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{secrets.github_token}}
          filter_mode: "file"
          fail_on_error: true
          level: "error"
          reporter: "github-pr-review"
          locale: "US"
          exclude: ./vendor/*
          pattern: "*.md"




