name: Check terraform file formatting
on:
  push:
    branches:
      - .github/workflows/pull_requests.yml
      - alicloud/*.go

jobs:
  check_format:
    runs-on: ubuntu-latest
    name: Check terraform file are formatted correctly
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: terraform fmt
        uses: dflook/terraform-fmt-check@v1
        with:
          path: website/docs
